/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.views.admin;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.BorderLayout;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import main.views.admin.Leaves.LeavesPage;
import main.views.admin.Salary.SalaryPage;
import main.views.admin.Settings.SettingsPage;
import main.views.admin.Dashboard.DashboardPage;
import main.views.admin.Employee.EmployeePage;

/**
 *
 * @author chari
 */

public class DForm extends javax.swing.JFrame {

    /**
     * Creates new form DForm
     */
    private DashboardPage DashPage;
    
    private EmployeePage EmpPage;
    
    private LeavesPage LeavPage;
    
    private SalaryPage SalPage;
    
    private SettingsPage SetingsPage;
    
    private Boolean Close =false;
   
    public DForm() {
        initComponents();
        
        // Initialize your pages
        DashPage = new DashboardPage();
        EmpPage = new EmployeePage();
        LeavPage = new LeavesPage();
        SalPage = new SalaryPage();
        SetingsPage = new SettingsPage();
        
        showForm(DashPage);
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int result = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Confirm Exit", JOptionPane.YES_NO_OPTION);
                Close = result == JOptionPane.YES_OPTION; 
                CconfirmExit();
            }
        });

        AdminMenu.setEvent((int index, int subIndex) -> {
            if (index == 0) {
                showForm(DashPage);
            }else if (index == 1){
                showForm(EmpPage);
            }
            else {
                showForm(DashPage);
            }
        });
        
    }

    private void CconfirmExit(){
        System.out.println(Close);
         if(Close){
            System.exit(0);
        }
    }
    
    private void showForm(JFrame frame){
        // Set the layout manager of viewPanel to BorderLayout
        viewPanel.setLayout(new BorderLayout());
        // Remove any previous frames
        viewPanel.removeAll();

        JInternalFrame internalFrame = new JInternalFrame();
        internalFrame.add(frame.getContentPane());
        internalFrame.setVisible(true);
        
       
        // Get the titlebar and set it to null
        setRootPaneCheckingEnabled(false);
        javax.swing.plaf.InternalFrameUI ifu= internalFrame.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)ifu).setNorthPane(null);
        

        // Set an empty border to remove the frame border
        internalFrame.setBorder(BorderFactory.createEmptyBorder());
        // Ensure that the internal frame covers the entire area
        internalFrame.setOpaque(true);

        // Listen for resizing events on both viewPanel and internalFrame
        viewPanel.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                internalFrame.setSize(viewPanel.getSize());
            }
        });

        internalFrame.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                internalFrame.setSize(viewPanel.getSize());
            }
        });

        // Add the internal frame to the viewPanel
        viewPanel.add(internalFrame, BorderLayout.CENTER);
        viewPanel.repaint();
        viewPanel.revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleBar = new javax.swing.JPanel();
        viewPanel = new javax.swing.JPanel();
        scrollPaneWin111 = new main.customeComponents.scroll.win11.ScrollPaneWin11();
        AdminMenu = new main.customeComponents.menu.Menu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashborad");
        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N

        titleBar.setBackground(new java.awt.Color(0, 20, 73));
        titleBar.setForeground(new java.awt.Color(2, 2, 59));

        javax.swing.GroupLayout titleBarLayout = new javax.swing.GroupLayout(titleBar);
        titleBar.setLayout(titleBarLayout);
        titleBarLayout.setHorizontalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        titleBarLayout.setVerticalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout viewPanelLayout = new javax.swing.GroupLayout(viewPanel);
        viewPanel.setLayout(viewPanelLayout);
        viewPanelLayout.setHorizontalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 866, Short.MAX_VALUE)
        );
        viewPanelLayout.setVerticalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 649, Short.MAX_VALUE)
        );

        scrollPaneWin111.setBorder(null);
        scrollPaneWin111.setViewportView(AdminMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrollPaneWin111, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(viewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(titleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        try {
            UIManager.setLookAndFeel( new FlatLightLaf() );
        } catch( UnsupportedLookAndFeelException ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DForm().setVisible(true);
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private main.customeComponents.menu.Menu AdminMenu;
    private main.customeComponents.scroll.win11.ScrollPaneWin11 scrollPaneWin111;
    private javax.swing.JPanel titleBar;
    private javax.swing.JPanel viewPanel;
    // End of variables declaration//GEN-END:variables
}
